#!/usr/bin/env python3
"""course.py — one-command driver for the course (phys-course-kit).

Verbs:
  build NN | --all [--keep-announcements] [--no-pa11y | --strict]
      Web target (PRIMARY): generate the root wrapper, run the BookML build,
      then the full check suite on the result.
  slides NN | --all
      Beamer PDF into build/slides/ (announcements sidecars always included —
      that is their point).  Also the dual-target regression gate.
  check NN | --all [--no-pa11y | --strict]
      Check suite only, on existing web builds.
  index
      Generate the site index (build/web/html/index.html) from the lecture
      titles scraped out of content/ — no separate manifest to maintain.
  doctor
      Toolchain sanity report.
  clean [--deep]
      Remove build outputs and generated wrappers; --deep also drops the
      bmlimages figure cache (forces re-rendering).

Lecture names are forgiving: 5, 05, lecture05 all work.

Toolchain stance: a full TeX Live plus latexml on PATH is all that is
expected — no pinning (verified: the kit runs on stock TeX Live 2026).
Set KIT_TEXBIN to prepend a specific TeX bin directory if you need one.
"""

import argparse
import glob
import os
import re
import shutil
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONTENT = ROOT / "content"
BUILD = ROOT / "build"
WEB_AUX = BUILD / "web"          # BookML AUX_DIR (set in GNUmakefile)
SITE = WEB_AUX / "html"          # built pages: SITE/lectureNN/index.html
SLIDES = BUILD / "slides"
BOOKML = ROOT / "bookml"


# ---------------------------------------------------------------------------
# environment
# ---------------------------------------------------------------------------

def base_env():
    env = os.environ.copy()
    texbin = env.get("KIT_TEXBIN")
    if texbin:
        env["PATH"] = texbin + os.pathsep + env["PATH"]
    return env


def pa11y_env():
    """On macOS, point puppeteer at a system browser unless the user already
    did (bundled-Chromium downloads are unreliable on some machines)."""
    env = base_env()
    if sys.platform == "darwin" and not env.get("PUPPETEER_EXECUTABLE_PATH"):
        for app in ("Google Chrome.app/Contents/MacOS/Google Chrome",
                    "Chromium.app/Contents/MacOS/Chromium",
                    "Microsoft Edge.app/Contents/MacOS/Microsoft Edge"):
            cand = Path("/Applications") / app
            if cand.exists():
                env["PUPPETEER_EXECUTABLE_PATH"] = str(cand)
                break
    return env


def run(cmd, env=None, cwd=ROOT, timeout=1800):
    p = subprocess.run(cmd, cwd=cwd, env=env or base_env(),
                       capture_output=True, text=True, timeout=timeout)
    return p.returncode, p.stdout + p.stderr


# ---------------------------------------------------------------------------
# course + lecture metadata (all scraped from the sources: no manifest)
# ---------------------------------------------------------------------------

def course_meta():
    meta = {}
    text = (ROOT / "shared" / "course.tex").read_text(encoding="utf-8")
    for m in re.finditer(r"\\newcommand\{\\(course\w+)\}\{([^}]*)\}", text):
        meta[m.group(1)] = m.group(2)
    return meta


def lectures():
    return sorted(p.stem[len("lecture"):]
                  for p in CONTENT.glob("lecture[0-9][0-9].tex"))


def norm_lecture(arg):
    m = re.fullmatch(r"(?:lecture)?(\d{1,2})", arg.strip())
    if not m:
        sys.exit(f"cannot parse lecture name: {arg!r}")
    nn = f"{int(m.group(1)):02d}"
    if not (CONTENT / f"lecture{nn}.tex").exists():
        sys.exit(f"no such lecture: content/lecture{nn}.tex")
    return nn


def lecture_title(nn):
    text = (CONTENT / f"lecture{nn}.tex").read_text(encoding="utf-8")
    m = re.search(r"\\kitlecturetitle\{((?:[^{}]|\{[^{}]*\})*)\}", text)
    return m.group(1).strip() if m else f"Lecture {int(nn)}"


# ---------------------------------------------------------------------------
# web build (BookML)
# ---------------------------------------------------------------------------

def write_wrapper(nn, keep_announcements=False):
    """Root-level lectureNN.tex wrapper for BookML.  Written only when the
    content differs, so make's dependency caching keeps working."""
    lines = ["%% GENERATED by course.py -- do not edit, do not commit",
             r"\def\kitlecture{" + nn + "}"]
    if keep_announcements:
        lines.append(r"\def\kitkeepannouncements{}")
    lines.append(r"\input{drivers/web.tex}")
    want = "\n".join(lines) + "\n"
    path = ROOT / f"lecture{nn}.tex"
    if not path.exists() or path.read_text(encoding="utf-8") != want:
        path.write_text(want, encoding="utf-8")
    return path


def build_web(nn, keep_announcements=False):
    if not BOOKML.is_dir():
        sys.exit("bookml/ is missing -- run the setup script (docs/setup.md)")
    write_wrapper(nn, keep_announcements)
    target = f"{WEB_AUX.relative_to(ROOT)}/html/lecture{nn}/index.html"
    print(f"  bookml: make {target}")
    rc, out = run(["make", target])
    (BUILD / "logs").mkdir(parents=True, exist_ok=True)
    (BUILD / "logs" / f"lecture{nn}.make.log").write_text(out, encoding="utf-8")
    if rc != 0:
        print(out[-2000:])
        print(f"BUILD FAILED (make exit {rc}) -- full log: build/logs/lecture{nn}.make.log")
        return False
    return True


# ---------------------------------------------------------------------------
# slides build (latexmk)
# ---------------------------------------------------------------------------

def build_slides(nn):
    SLIDES.mkdir(parents=True, exist_ok=True)
    job = f"lecture{nn}-slides"
    cmd = ["latexmk", "-pdf", f"-usepretex=\\def\\kitlecture{{{nn}}}",
           f"-jobname={job}", f"-output-directory={SLIDES.relative_to(ROOT)}",
           "-interaction=nonstopmode", "-halt-on-error", "drivers/slides.tex"]
    rc, out = run(cmd)
    if rc != 0:
        print(out[-1500:])
        print(f"SLIDES FAILED (latexmk exit {rc})")
        return False
    run(["latexmk", "-c", f"-jobname={job}",
         f"-output-directory={SLIDES.relative_to(ROOT)}", "drivers/slides.tex"])
    for ext in (".nav", ".snm", ".vrb"):  # beamer extras latexmk -c leaves
        p = SLIDES / (job + ext)
        if p.exists():
            p.unlink()
    print(f"  slides OK -> build/slides/{job}.pdf")
    return True


# ---------------------------------------------------------------------------
# check suite
# ---------------------------------------------------------------------------

MATHML_TOKENS = {"mi", "mo", "mn", "mtext", "ms", "mspace",
                 "annotation", "annotation-xml"}


class _MathScan(HTMLParser):
    """Character data directly inside a non-token MathML element — the
    malformed-MathML signature (donor course tripwire, kept as insurance)."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack, self.in_math, self.bare = [], 0, []

    def handle_starttag(self, tag, attrs):
        self.stack.append(tag)
        if tag == "math":
            self.in_math += 1

    def handle_endtag(self, tag):
        while self.stack:
            if self.stack.pop() == tag:
                break
        if tag == "math":
            self.in_math = max(0, self.in_math - 1)

    def handle_data(self, data):
        if self.in_math and data.strip():
            parent = self.stack[-1] if self.stack else "?"
            if parent not in MATHML_TOKENS:
                self.bare.append((parent, data.strip()[:40]))


def bare_math_text(html_text):
    s = _MathScan()
    s.feed(html_text)
    return s.bare


def libgs_available():
    rc, out = run(["dvisvgm", "-V1"], timeout=60)
    return rc == 0 and "Ghostscript" in out


def pa11y_page(path, strict, skip):
    if skip:
        return True, "skipped"
    exe = shutil.which("pa11y")
    if not exe:
        if strict:
            return False, "pa11y NOT INSTALLED (required by --strict)"
        return True, "pa11y not installed -- skipping (npm install -g pa11y)"
    rc, out = run([exe, "--runner", "axe", "--hide-elements", "math",
                   path.resolve().as_uri()], env=pa11y_env(), timeout=300)
    if rc == 0:
        return True, "No issues found"
    if rc == 2:
        return False, "ACCESSIBILITY ISSUES:\n" + out[-1200:]
    return (not strict), f"TECHNICAL FAILURE (exit {rc}) -- browser/launch problem, not an audit result"


def check_lecture(nn, strict=False, no_pa11y=False):
    page_dir = SITE / f"lecture{nn}"
    ok = True
    if not (page_dir / "index.html").exists():
        print(f"  MISSING: {page_dir}/index.html (build it first)")
        return False

    # latexml log: errors, with the known libgs/depth class told apart
    log = WEB_AUX / "latexmlaux" / f"lecture{nn}.latexml.log"
    if log.exists():
        text = log.read_text(encoding="utf-8", errors="replace")
        errors = re.findall(r"^Error:(\S+)", text, re.M)
        dpth = [e for e in errors if e.startswith("expected:dpth")]
        other = [e for e in errors if not e.startswith("expected:dpth")]
        if other:
            print(f"  latexml: {len(other)} error(s) -- {sorted(set(other))}")
            ok = False
        if dpth:
            if libgs_available():
                print(f"  latexml: {len(dpth)} image-depth error(s) WITH libgs present -- investigate")
                ok = False
            else:
                print(f"  latexml: {len(dpth)} image-depth error(s) (dvisvgm has no Ghostscript library; "
                      "baseline-only, harmless for display figures -- install ghostscript to clear)")
    else:
        print("  latexml log missing")
        ok = False

    # page-level tripwires
    n_math = n_unparsed = n_imgs = 0
    for page in sorted(page_dir.glob("*.html")):
        html_text = page.read_text(encoding="utf-8", errors="replace")
        missing = html_text.count("[ALT MISSING")
        if missing:
            print(f"  {page.name}: {missing} [ALT MISSING] figure description(s)")
            ok = False
        for m in re.finditer(r"<img\b[^>]*>", html_text):
            tag = m.group(0)
            if "ltx_graphics" in tag:
                n_imgs += 1
                if re.search(r'alt=""', tag):
                    print(f"  {page.name}: figure <img> with EMPTY alt")
                    ok = False
        bare = bare_math_text(html_text)
        if bare:
            print(f"  {page.name}: bare-math-text {len(bare)} -- {bare[:3]}")
            ok = False
        n_math += html_text.count("<math")
        n_unparsed += html_text.count("ltx_math_unparsed")

    print(f"  checks: <math> {n_math} | unparsed {n_unparsed} | figures {n_imgs} | bare-math-text 0"
          if ok else f"  checks: <math> {n_math} | unparsed {n_unparsed} | figures {n_imgs}")

    # pa11y, every page
    for page in sorted(page_dir.glob("*.html")):
        good, msg = pa11y_page(page, strict, no_pa11y)
        if not good:
            print(f"  pa11y {page.name}: {msg}")
            ok = False
    if not no_pa11y:
        print("  pa11y: clean" if ok else "  pa11y: see above")
    return ok


# ---------------------------------------------------------------------------
# index
# ---------------------------------------------------------------------------

def build_index(strict=False, no_pa11y=False):
    meta = course_meta()
    rows = [(nn, lecture_title(nn)) for nn in lectures()]
    items = "\n".join(
        f"      <li><a href='lecture{nn}/index.html'>Lecture {int(nn)} — {title}</a></li>"
        for nn, title in rows)
    page = f"""<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{meta.get('coursecode', '')} — {meta.get('coursetitle', '')}</title>
<style>
  body {{ font-family: Georgia, serif; max-width: 42rem; margin: 2rem auto; padding: 0 1rem; color: #111827; }}
  h1 {{ color: #13294B; font-size: 1.5rem; }}
  nav ol {{ list-style: none; padding-left: 0; }}
  nav li {{ margin: 0.4rem 0; }}
  a {{ color: #13294B; }}
</style>
</head>
<body>
  <header>
    <h1>{meta.get('coursecode', '')} — {meta.get('coursetitle', '')}</h1>
    <p>Accessible HTML lecture notes, one page per lecture. {meta.get('courseterm', '')}.</p>
  </header>
  <nav aria-label="Lectures">
    <ol role="list">
{items}
    </ol>
  </nav>
</body>
</html>
"""
    SITE.mkdir(parents=True, exist_ok=True)
    out = SITE / "index.html"
    out.write_text(page, encoding="utf-8")
    print(f"index: {len(rows)} lecture(s) -> {out.relative_to(ROOT)}")
    good, msg = pa11y_page(out, strict, no_pa11y)
    print(f"  pa11y: {msg}" if isinstance(msg, str) else "")
    return good


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------

def doctor():
    ok = True

    def probe(name, cmd, required=True, note=""):
        nonlocal ok
        exe = shutil.which(cmd[0])
        if not exe:
            print(f"  {'MISSING' if required else 'absent '}: {name}" + (f" ({note})" if note else ""))
            if required:
                ok = False
            return None
        rc, out = run(cmd, timeout=60)
        ver = out.strip().splitlines()[0] if out.strip() else ""
        print(f"  ok: {name} -- {ver[:70]}" + (f" ({note})" if note else ""))
        return out

    print("toolchain (stock PATH is the expectation; KIT_TEXBIN overrides):")
    probe("make", ["make", "--version"])
    probe("latexmk", ["latexmk", "--version"])
    probe("pdflatex", ["pdflatex", "--version"])
    probe("latexml", ["latexml", "--VERSION"], note="kit validated on 0.8.8 + classic-TeX preamble")
    dv = probe("dvisvgm", ["dvisvgm", "-V1"])
    if dv is not None and "Ghostscript" not in dv:
        print("  warn: dvisvgm has NO Ghostscript library (libgs) -- BookML image-depth "
              "errors expected (baseline-only); install ghostscript to clear")
    for sty in ("preview.sty", "comment.sty"):
        rc, out = run(["kpsewhich", sty], timeout=60)
        if rc == 0 and out.strip():
            print(f"  ok: {sty} -- {out.strip().splitlines()[0]}")
        else:
            print(f"  MISSING: {sty} (BookML needs it; install the TeX package)")
            ok = False
    if BOOKML.is_dir():
        print(f"  ok: bookml/ present")
    else:
        print("  MISSING: bookml/ -- fetch the pinned release (docs/setup.md)")
        ok = False
    if shutil.which("pa11y"):
        env = pa11y_env()
        browser = env.get("PUPPETEER_EXECUTABLE_PATH", "(puppeteer default)")
        print(f"  ok: pa11y -- browser: {browser}")
    else:
        print("  absent : pa11y (accessibility audits skipped; npm install -g pa11y)")

    meta = course_meta()
    print(f"course: {meta.get('coursecode', '?')} — {meta.get('coursetitle', '?')} "
          f"({meta.get('courseterm', '?')})")
    lex = lectures()
    print(f"content: {len(lex)} lecture(s): {', '.join(lex)}")
    for nn in lex:
        print(f"  lecture{nn}: {lecture_title(nn)}")
    return ok


# ---------------------------------------------------------------------------
# clean
# ---------------------------------------------------------------------------

def clean(deep=False):
    for p in [BUILD] + sorted(ROOT.glob("lecture[0-9][0-9].tex")) \
            + sorted(ROOT.glob("*.zip")):
        if isinstance(p, Path) and p.exists():
            shutil.rmtree(p) if p.is_dir() else p.unlink()
            print(f"  removed {p.relative_to(ROOT)}")
    if deep:
        for p in (ROOT / "bmlimages",):
            if p.exists():
                shutil.rmtree(p)
                print(f"  removed {p.relative_to(ROOT)} (figure cache)")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("verb", choices=["build", "slides", "check", "index", "doctor", "clean"])
    ap.add_argument("lecture", nargs="?", help="NN / lectureNN (or --all)")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--keep-announcements", action="store_true")
    ap.add_argument("--strict", action="store_true", help="missing pa11y is an error")
    ap.add_argument("--no-pa11y", action="store_true")
    ap.add_argument("--deep", action="store_true", help="clean: also drop the figure cache")
    args = ap.parse_args()

    if args.verb == "doctor":
        sys.exit(0 if doctor() else 1)
    if args.verb == "clean":
        clean(args.deep)
        return
    if args.verb == "index":
        sys.exit(0 if build_index(args.strict, args.no_pa11y) else 1)

    targets = lectures() if args.all else [norm_lecture(args.lecture or "")] \
        if (args.lecture or args.all) else sys.exit("give a lecture (NN) or --all")

    results = {}
    for nn in targets:
        print(f"== lecture{nn} ==")
        if args.verb == "slides":
            results[nn] = build_slides(nn)
        elif args.verb == "build":
            good = build_web(nn, args.keep_announcements)
            if good:
                good = check_lecture(nn, args.strict, args.no_pa11y)
            results[nn] = good
            print(("PASS" if good else "FAIL") + f" lecture{nn}")
        elif args.verb == "check":
            results[nn] = check_lecture(nn, args.strict, args.no_pa11y)
            print(("PASS" if results[nn] else "FAIL") + f" lecture{nn}")
    if args.verb == "build" and args.all:
        build_index(args.strict, args.no_pa11y)
    n_ok = sum(results.values())
    print(f"\n{n_ok}/{len(results)} PASS")
    sys.exit(0 if n_ok == len(results) else 1)


if __name__ == "__main__":
    main()
